- id: '1504800743460'
  alias: trigger light auto
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.test
    to: 'on'
  action:
    service: switch.turn_on
    entity_id:
    - switch.led
    - switch.lounge_light

- id: lounge light on
  initial_state: 'on'
  alias: Turn lounge Light On At Sunset
  trigger:
    platform: sun
    event: sunset
    offset: -00:30
  action:
    service: switch.turn_on
    entity_id: switch.lounge_light

- id: lounge light off
  initial_state: 'on'
  alias: Turn lounge Light Off 22:30
  trigger:
    platform: time
    at: '22:30'
  action:
    service: switch.turn_off
    entity_id: switch.lounge_light

- id: lounge side light off
  initial_state: 'on'
  alias: Turn lounge side Light Off 22:45
  trigger:
    platform: time
    at: '22:45'
  action:
    service: switch.turn_off
    entity_id: switch.lounge_side_lamp
