- action:
  - alias: ''
    data:
      entity_id: lounge_side_lamp
    service: switch.turn_on
  alias: Turn on lounge lights
  condition: []
  id: '1504626744268'
  trigger:
  - event: sunset
    offset: -00:30
    platform: sun
- action:
  - data:
      entity_id: main_bedroom_side_lamp
    service: Switch.turn_on
  alias: lamp on at dawn
  condition: []
  id: '1504729527077'
  trigger:
  - event: sunrise
    platform: sun
