- id: '1504800743460'
  alias: trigger led on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.pirlounge
    to: 'on'
  action:
    service: switch.turn_on
    entity_id:  switch.led

- id: '1504800743460'
  alias: trigger led off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.pirlounge
    to: 'off'
    for: 00:00:30
  action:
    service: switch.turn_off
    entity_id:  switch.led

- id: lounge light on
  initial_state: 'on'
  alias: Turn lounge Light On At Sunset
  trigger:
    platform: sun
    event: sunset
    offset: -00:30
  action:
    service: switch.turn_on
    entity_id: switch.lounge_light

- id: lounge light off
  initial_state: 'on'
  alias: Turn lounge Light Off 22:30
  trigger:
    platform: time
    at: '22:30'
  action:
    service: switch.turn_off
    entity_id: switch.lounge_light

- id: lounge side light off
  initial_state: 'on'
  alias: Turn lounge side Light Off 22:45
  trigger:
    platform: time
    at: '22:45'
  action:
    service: switch.turn_off
    entity_id: switch.lounge_side_lamp

- id: lounge movement Detected
  initial_state: 'on'
  alias: Turn on lounge movement detected
  trigger:
    platform: state
    entity_id: binary_sensor.pirlounge
    to: 'on'


  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.lounge_side_lamp
        state: "off"
      - condition: state
        entity_id: switch.lounge_light
        state: "on"

  action:
    service: switch.turn_on
    entity_id: switch.lounge_side_lamp


- id: lounge movement not Detected
  initial_state: 'on'
  alias: Turn off lounge side light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.pirlounge
    to: 'off'
    for: 00:10:40
  action:
    service: switch.turn_off
    entity_id: switch.lounge_side_lamp
